# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: todos-aws

provider:
  name: aws
  runtime: go1.x
  profile: cameron
  region: ap-southeast-2

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  get:
    handler: bin/get

    events:
      - http:
          path: todos/{id}
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: false
  index:
    handler: bin/index
    events:
      - http:
          path: todos
          method: get
          cors: true
  post:
    handler: bin/create
    events:
      - http:
          path: todos
          method: post
          cors: true
